name: elo7_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  webview_flutter: ^4.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  icons_launcher: ^2.1.7


flutter_native_splash:
  color: "#fdb933"
  image: "assets/app/splash.png"
  android: true
  ios: true

  android_12:
    color: "#fdb933"
    image: "assets/app/icon.png"


icons_launcher:
  image_path: "assets/app/icon.png"
  adaptive_background_color: '#fdb933'
  adaptive_background_image	:   'assets/app/icon.png'
  adaptive_foreground_image: 'assets/app/icon.png'
  adaptive_round_image: 'assets/app/icon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true

# flutter_launcher_icons:
#   image_path: "assets/app/icon.png"
#   ios: true
#   remove_alpha_ios: true
#   android: "launcher_icon"
#   adaptive_icon_background: "#fdb933"
#   adaptive_icon_foreground: "assets/app/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11



# build_runner:
#   # Indica que os arquivos gerados devem ser colocados na pasta 'test/mock'
#   generate_for:
#     - lib/**/*.dart
#   options:
#     # Especifica o diretório de saída dos arquivos gerados
#     output: test/mock


flutter:
  uses-material-design: true

  assets:
    - assets/images/highlight/
    - assets/images/sellers/
    
  fonts:
    - family: Museo Sans
      fonts:
        - asset: assets/fonts/MuseoSans-300.otf
