name: elo7_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  mockito: ^5.4.4
  build_runner: ^2.4.11
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/highlight/
    - assets/images/sellers/

  fonts:
    - family: Museo Sans
      fonts:
        - asset: assets/fonts/MuseoSans-300.otf
